#!/system/bin/sh
export RISH_APPLICATION_ID="com.termux"
DEX="/data/data/com.termux/files/home/.Shizuku/rish_shizuku.dex"

if [ ! -f "$DEX" ]; then
  echo "Cannot find $DEX"
  exit 1
fi

# Android 14+ Security Lock
if [ $(getprop ro.build.version.sdk) -ge 34 ]; then
  chmod 400 "$DEX"
fi

/system/bin/app_process -Djava.class.path="$DEX" /system/bin --nice-name=rish rikka.shizuku.shell.ShizukuShellLoader "$@"
